# Exploration — Motifs de sanction ACPR

Objectif : reconstruire le texte complet de chaque décision (recollage des chunks),
observer la fréquence des segments de motif bruts, et lire le texte des décisions
à motif vide ou particulier pour leur attribuer un motif par analogie.

Prérequis venv local : `google-cloud-bigquery`, `pandas`, `jupyter`.

In [1]:
import json
from collections import Counter
from pathlib import Path

import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account

# ── Config — ajuste le chemin si ton venv training n'est pas au même niveau ──
GCP_PROJECT_ID = "gen-lang-client-0989575872"
GCP_SA_KEY_PATH = Path("../../../gcp_sa_banque.json")  # racine du MVP banque-de-france
BQ_DATASET = "banque_de_france_veille"
BQ_TABLE = "articles_bruts"

# EXPORT_DIR = Path("exploration")
# EXPORT_DIR.mkdir(exist_ok=True)

In [2]:
# ── Connexion BigQuery ──
credentials = service_account.Credentials.from_service_account_file(
    str(GCP_SA_KEY_PATH),
    scopes=["https://www.googleapis.com/auth/cloud-platform"],
)
client = bigquery.Client(project=GCP_PROJECT_ID, credentials=credentials)

query = f"""
    SELECT id, title, date, content, metadata
    FROM `{GCP_PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}`
    WHERE source = 'acpr_decision'
"""

df = client.query(query).to_dataframe()
print(f"{len(df)} chunks récupérés")
df.head()

c:\Users\iandr\Documents\EXP\exp 2.0\projet cv\presentation-portefolio\realisations\banque-de-france\training\venv-banque-training\Lib\site-packages\google\cloud\bigquery\table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

1924 chunks récupérés

,id,title,date,content,metadata
0,banque_acpr_2025-01_chunk_0,Décision de la Commission des sanctions n°2025...,2026-05-13,Décision de la Commission des sanctions – proc...,"{""url"": ""https://acpr.banque-france.fr/system/..."
1,banque_acpr_2025-01_chunk_1,Décision de la Commission des sanctions n°2025...,2026-05-13,intérieur de la Commission des sanctions ; La ...,"{""url"": ""https://acpr.banque-france.fr/system/..."
2,banque_acpr_2025-01_chunk_2,Décision de la Commission des sanctions n°2025...,2026-05-13,d’un contrôle sur place par les services du se...,"{""url"": ""https://acpr.banque-france.fr/system/..."
3,banque_acpr_2025-01_chunk_3,Décision de la Commission des sanctions n°2025...,2026-05-13,millions d’euros de primes acquises pour l’ass...,"{""url"": ""https://acpr.banque-france.fr/system/..."
4,banque_acpr_2025-01_chunk_4,Décision de la Commission des sanctions n°2025...,2026-05-13,"et II du livre premier, cet article ne fait pa...","{""url"": ""https://acpr.banque-france.fr/system/..."

In [3]:
# ── Parsing des métadonnées JSON (decision_number, chunk_index, motif) ──
def parse_metadata(row):
    meta = json.loads(row["metadata"])
    return pd.Series({
        "decision_number": meta.get("decision_number", ""),
        "chunk_index": meta.get("chunk_index", 0),
        "motif": meta.get("motif", ""),
    })

meta_df = df.apply(parse_metadata, axis=1)
df = pd.concat([df, meta_df], axis=1)
df.head()

,id,title,date,content,metadata,decision_number,chunk_index,motif
0,banque_acpr_2025-01_chunk_0,Décision de la Commission des sanctions n°2025...,2026-05-13,Décision de la Commission des sanctions – proc...,"{""url"": ""https://acpr.banque-france.fr/system/...",2025-01,0,protection de la clientèle ; respect des oblig...
1,banque_acpr_2025-01_chunk_1,Décision de la Commission des sanctions n°2025...,2026-05-13,intérieur de la Commission des sanctions ; La ...,"{""url"": ""https://acpr.banque-france.fr/system/...",2025-01,1,protection de la clientèle ; respect des oblig...
2,banque_acpr_2025-01_chunk_2,Décision de la Commission des sanctions n°2025...,2026-05-13,d’un contrôle sur place par les services du se...,"{""url"": ""https://acpr.banque-france.fr/system/...",2025-01,2,protection de la clientèle ; respect des oblig...
3,banque_acpr_2025-01_chunk_3,Décision de la Commission des sanctions n°2025...,2026-05-13,millions d’euros de primes acquises pour l’ass...,"{""url"": ""https://acpr.banque-france.fr/system/...",2025-01,3,protection de la clientèle ; respect des oblig...
4,banque_acpr_2025-01_chunk_4,Décision de la Commission des sanctions n°2025...,2026-05-13,"et II du livre premier, cet article ne fait pa...","{""url"": ""https://acpr.banque-france.fr/system/...",2025-01,4,protection de la clientèle ; respect des oblig...

In [4]:
# ── Reconstruction du texte complet par décision (chunks recollés dans l'ordre) ──
def reconstruct_documents(df: pd.DataFrame) -> dict:
    documents = {}
    for decision_number, group in df.groupby("decision_number"):
        ordered = group.sort_values("chunk_index")
        full_text = "\n\n".join(ordered["content"].tolist())
        documents[decision_number] = {
            "title": ordered.iloc[0]["title"],
            "date": ordered.iloc[0]["date"],
            "motif": ordered.iloc[0]["motif"],
            "text": full_text,
            "n_chunks": len(ordered),
        }
    return documents

documents = reconstruct_documents(df)
print(f"{len(documents)} décisions reconstruites")

105 décisions reconstruites

In [5]:
# ── Tableau de fréquence des segments de motif bruts ──
segment_counter = Counter()
for doc in documents.values():
    if not doc["motif"]:
        continue
    segments = [s.strip().lower() for s in doc["motif"].split(";") if s.strip()]
    segment_counter.update(segments)

freq_df = pd.DataFrame(segment_counter.most_common(), columns=["segment", "count"])
freq_df

                                              segment  count
0   lutte contre le blanchiment des capitaux et le...     56
1                                    contrôle interne     15
2                             établissement de crédit     12
3                           établissement de paiement      6
4                          protection de la clientèle      5
..                                                ...    ...
64                               maîtrise des risques      1
65                         lutte contre la déshérence      1
66                      relations avec le superviseur      1
67                 établissement de paiement étranger      1
68  respect des obligations d’information précontr...      1

[69 rows x 2 columns]

In [8]:
# ── Décisions à motif vide ou particulier — à lire pour attribution par analogie ──
SPECIAL_CASES = ["2010-01", "2012-04", "2013-01", "2015-02", "2018-06", "2019-02", "2021-05", "2014-04"]

for dn in SPECIAL_CASES:
    doc = documents.get(dn)
    if not doc:
        print(f"⚠️  {dn} — introuvable dans le corpus reconstruit")
        continue
    print("=" * 80)
    print(f"{dn} — {doc['title']} ({doc['date']}) — {doc['n_chunks']} chunks")
    print("=" * 80)
    print(doc["text"][:3000])
    print("\n[...texte tronqué à 3000 caractères, voir export si besoin de plus...]\n")

================================================================================
2010-01 — Décision de la Commission des sanctions n° 2010-01 du 10 janvier 2011 à l'égard de la CAISSE DE CREDIT MUNICIPAL DE TOULON (2011-01-10) — 21 chunks
================================================================================
CAISSE DE CRÉDIT MUNICIPAL DE TOULON (CCMT) ----- Procédure n° 2010-01 Blâme et sanction pécuniaire de 150 000 euros ----- Audition du 16 décembre 2010 Rendue le 10 janvier 2011 ----- AUTORITÉ DE CONTRÔLE PRUDENTIEL COMMISSION DES SANCTIONS _____________ Vu […] ; La Commission des sanctions de l’Autorité de contrôle prudentiel, composée de M. MARTIN LAPRADE, Président, de Mme ALDIGÉ et de MM. CREDOT, FLORIN et ICARD, membres ; Après avoir décidé de faire droit à la demande de la CCMT tendant à ce que l’audience ne soit pas publique et entendu, lors de la séance du 16 décembre 2010 : – M. Jean-Manuel CLEMMER, chargé de la mise en état, en sa présentation du dossier, assisté de M. Clément ROUXEL, juriste du service de la commission des sanctions ; – M. Antoine SAINTOYANT, représentant le directeur général du Trésor, qui a indiqué ne pas avoir d’observations à formuler ; – M. Christian POIRIER, représentant le Collège de l’ACP, assisté de M. Édouard FERNANDEZ-BOLLO, secrétaire général adjoint de l’ACP, M. Henry de GANAY, directeur des affaires juridiques de l’ACP et M. Fabrice JEANNE, collaborateur de cette direction ; – M. Jean-Pierre GOUALLEC, Vice-président du COS de la CCMT, et M. Christian GUEHO, directeur de cette caisse ; Au cours de la séance, M. POIRIER a proposé que soient infligés à la CCMT un blâme et une sanction pécuniaire de 150 000 euros ; Les personnes mises en cause ayant eu la parole en dernier ; Après en avoir délibéré en la seule présence de ses membres ; Considérant qu’il résulte du dossier, et notamment de la lettre du 4 mars 2004 adressée par le Secrétaire général de la Commission bancaire à la suite du rapport de M. AGOUTIN, Inspecteur général de la Banque de France, que la CCMT présentait déjà à cette date des insuffisances dans le suivi de ses risques et l’organisation de son dispositif de contrôle interne ; que cette lettre insistait sur la nécessité de remettre à niveau le système d’information et d’apporter de substantielles améliorations en matière comptable ; qu’elle rappelait que le rapport d’inspection de 2003 mettait en évidence la persistance de la plupart des lacunes déjà soulignées dans un précédent rapport, établi en 1998 ; que selon le rapport signé le 29 octobre 2009 par Mme PINZUTI, Inspecteur de la Banque de France, l’établissement n’aurait pas procédé aux mises à niveau Autorité de contrôle prudentiel – Commission des sanctions 2 nécessaires malgré les observations insistantes du Secrétariat général de la Commission bancaire qui l’avait invité « à une réaction vigoureuse et déterminée » ; 1. Sur le respect des règles de gouvernance Considérant que les alinéas 5 et 7 de l’article L. 514-2 du Code monétaire et financier prévoient notamment que le COS définit les orientations générales ainsi que les règles d’organisation de la caisse de crédit municipal et exerce le contrôle permanent de la gestion de l’établissement par le directeur, qu’il veille au respect des réglementations générales de la profession banc

[...texte tronqué à 3000 caractères, voir export si besoin de plus...]

================================================================================
2012-04 — Décision de la commission des sanctions n° 2012-04 du 10 janvier 2013 à l'égard de la Banque Populaire Côte d'Azur (2013-01-10) — 37 chunks
================================================================================
Décision de la Commission des sanctions – procédures nos 2012-04 et 2012-04 bis Autorité de contrôle prudentiel – Commission des sanctions 1 BANQUE POPULAIRE CÔTE D’AZUR Procédures nos 2012-04 et 2012-04 bis ––––– Blâme et sanction pécuniaire de 500 000 euros ––––– Audience du 18 décembre 2012 rendue le 10 janvier 2013 AUTORITÉ DE CONTRÔLE PRUDENTIEL COMMISSION DES SANCTIONS –––––––––– Vu la lettre du 10 mai 2012 par laquelle le Président de l’Autorité de contrôle prudentiel (ACP) informe la commission de ce que le Collège de l’ACP, statuant en sous-collège sectoriel de la banque, a décidé, lors de sa séance du 3 mai 2012, d’ouvrir une procédure disciplinaire à l’encontre de la BANQUE POPULAIRE CÔTE D’AZUR (ci-après BPCA), enregistrée sous le numéro 2012-04 ; Vu la notification de griefs du 10 mai 2012 ; Vu les mémoires distincts déposés dans la procédure n° 2012-04 bis les 2 juillet, 8 octobre et 29 novembre 2012, par lesquels la BPCA demande à la commission de transmettre au Conseil d’État trois questions prioritaires de constitutionnalité (ci-après QPC), tirées respectivement de l’absence de prescription des infractions disciplinaires, de la non-séparation des fonctions de poursuite et d’instruction au sein de l’ACP et de l’absence de disposition interdisant à l’auteur de la saisine de participer au délibéré de la Commission des sanctions ; Vu le mémoire distinct du 10 septembre 2012, par lequel M. Olivier FOUQUET, représentant du Collège de l’ACP, conclut à l’irrecevabilité de la QPC soulevée par la BPCA et, subsidiairement, à son manque de sérieux ; Vu les mémoires en défense déposés dans la procédure n° 2012-04 les 2 juillet, 8 octobre et 5 novembre 2012 et les pièces qui les accompagnent, par lesquels la BPCA (i) demande à la Commission des sanctions, à titre liminaire, d’une part, de surseoir à statuer jusqu’à la purge de la procédure relative à la première QPC dont elle l’a saisie et enregistrée sous le n° 2012-04 bis et, d’autre part, d’annuler la procédure disciplinaire engagée par le collège pour divers motifs liés à la procédure, (ii) soutient, au fond, que les griefs notifiés manquent de fondement en droit comme en fait et (iii) sollicite la publicité des débats relatifs aux exceptions de procédure précitées, ainsi que de la décision à intervenir ; Vu les mémoires des 10 septembre et 23 octobre 2012, par lesquels M. Olivier FOUQUET, représentant du Collège de l’ACP, (i) conclut au rejet des exceptions de procédure soulevées par la BPCA, (ii) maintient l’ensemble des griefs notifiés et (iii) rappelle que la publicité de l’audience est la règle, sous réserve de la décision du Président de la commission d’interdire au public l’accès de la salle pendant tout ou partie de l’audience dans l’intérêt de la moralité, de l’ordre public, de la sécurité nationale ou lorsque la protection des secrets des affaires ou de tout autre secret protégé par la loi l’exige ; Le Conseil d’Etat a rejeté le recours formé par la Banque populaire Côte-d’Azur c

[...texte tronqué à 3000 caractères, voir export si besoin de plus...]

================================================================================
2013-01 — Décision de la Commission des sanctions n°2013-01 du 25 novembre 2013 à l’égard de la CAISSE D’EPARGNE ET DE PREVOYANCE DU LANGUEDOC-ROUSSILLON (2013-11-25) — 36 chunks
================================================================================
CAISSE D’ÉPARGNE ET DE PRÉVOYANCE DU LANGUEDOC-ROUSSILLON Procédure no 2013-01 ----- Blâme et sanction pécuniaire de 1 000 000 d’euros ----- Audience du 4 novembre 2013 Décision rendue le 25 novembre 2013 AUTORITÉ DE CONTRÔLE PRUDENTIEL ET DE RÉSOLUTION COMMISSION DES SANCTIONS –––––––––– Vu la lettre du 15 janvier 2013 (et les pièces qui lui sont annexées) par laquelle le Président de l’Autorité de contrôle prudentiel (ACP), informe la Commission de ce que le Collège de l’ACP, statuant en sous- collège sectoriel de la banque, a décidé, lors de sa séance du 17 décembre 2012, d’ouvrir une procédure disciplinaire à l’encontre de la CAISSE D’ÉPARGNE ET DE PRÉVOYANCE DU LANGUEDOC- ROUSSILLON (ci-après la CELR), ayant son siège social 254 rue Michel Teule, ZAC d’Alco, BP 7330, 34184 Montpellier Cedex 4, enregistrée sous le numéro 2013-01 ; Vu la notification de griefs du 15 janvier 2013 ; Vu les mémoires en défense des 27 mars, 19 juillet et 12 septembre 2013, ainsi que les pièces qui les accompagnent, par lesquels la CELR (i) présente une demande de renvoi préjudiciel pour interprétation par la Cour de justice de l’Union européenne (ci-après la CJUE) de la portée de la Charte des droits fondamentaux de l’Union européenne, (ii) soulève la nullité de l’« enquête », du rapport « d’enquête » et de la notification de griefs, (iii) conteste que les griefs notifiés soient constitutifs de manquements susceptibles de sanctions et (iv) sollicite, d’une part, que l’audience devant la Commission ne soit pas publique et, d’autre part, que la décision à intervenir ne soit pas publiée sous une forme nominative ; Vu les mémoires des 3 juin et 26 août 2013, par lesquels M. Olivier FOUQUET, représentant le Collège, conclut que la Commission ne doit pas transmettre à la CJUE la question préjudicielle posée par la CELR, estime que les exceptions de procédure doivent être rejetées et maintient l’ensemble des griefs notifiés ; Vu le rapport du 3 octobre 2013 de M. Charles CORNUT, rapporteur, dans lequel celui-ci conclut (i) qu’il n’y a pas de raison sérieuse conduisant à renvoyer à la CJUE la question préjudicielle posée, (ii) que les exceptions de procédure doivent être écartées et (iii) au fond, que sont établis les griefs 2.2 et 2.5 (sur le système automatisé de surveillance et de détection des opérations atypiques), les griefs 4 à 12 (défauts de déclaration de soupçon – ci-après DS), ainsi que 19 (sur le dispositif de contrôle permanent de premier niveau), 20 et 21 (sur le dispositif de contrôle permanent de second niveau) ; que sont également fondés mais dans un périmètre réduit les griefs 1 (sur la classification des risques), 2.1 et 2.3 (sur le système automatisé de surveillance et de détection des opérations atypiques), 13 à 17 (DS tardives), ainsi que 18 (sur le dispositif de contrôle permanent de premier niveau) ; que doivent être écartés le grief 2.4 (sur le système automatisé de surveillance et de détection des opérations atypiques) et le grief 3 (sur le trait

[...texte tronqué à 3000 caractères, voir export si besoin de plus...]

================================================================================
2015-02 — Décision de la Commission des sanctions - Procédures n° 2015-02 et n° 2015-03 du 11 mars 2016 (2016-03-11) — 19 chunks
================================================================================
SOCIETE C Venant aux droits de la SOCIETE A Procédure no 2015-02 Sanction pécuniaire de 100 000 euros SOCIETE B Procédure no 2015-03 Avertissement et sanction pécuniaire de 100 000 euros Audience du 19 février 2016 Décision rendue le 11 mars 2016 AUTORITÉ DE CONTRÔLE PRUDENTIEL ET DE RÉSOLUTION COMMISSION DES SANCTIONS –––––––––– Vu les lettres du 2 mars 2015 par lesquelles le Président de l’Autorité de contrôle prudentiel et de résolution (ci-après l’ACPR) informe la Commission de ce que le Collège de supervision de l’ACPR (ci-après le Collège), statuant en sous-collège sectoriel de l’assurance, a décidé, lors de sa séance du 12 février 2015, d’ouvrir deux procédures disciplinaires, la première à l’encontre de la société A et la seconde à l’encontre de la société B, respectivement enregistrées sous les numéros 2015-02 et 2015-03 ; Vu les notifications de griefs du 2 mars 2015 ; Vu les lettres du 12 juin 2014, par lesquelles le Collège met en demeure :  la société A (i) de se conformer aux dispositions de l’article R. 322-84 du code des assurances relatives au nombre minimum d’adhérents que doit comporter une société de réassurance mutuelle ; (ii) de modifier les clauses de ses traités de réassurance d’adhésion contraires aux exigences de l’article R. 322-53-2 du même code ;  la société B de modifier plusieurs de ses dispositions statutaires afin de se conformer aux prescriptions (i) des articles R. 322-58, R. 322-82 et L. 322-26-2-1 du code des assurances s’agissant du fonctionnement de son assemblée générale ; (ii) des articles L. 322-26-2 et R. 322-55-2 du même code s’agissant du fonctionnement de son conseil d’administration ; Vu les mémoires en défense des 22 juin 2015, et 10 septembre 2015, ainsi que les pièces qui les accompagnent, par lesquels :  la société A (i) conteste le grief relatif au nombre minimum d’adhérents que doit comporter une société de réassurance mutuelle ; (ii) conteste le grief tenant à l’illégalité de certaines clauses de ses traités d’adhésion ; (iii) fait valoir, s’agissant du grief relatif au non-respect de la mise en demeure précitée, qu’elle ne saurait être sanctionnée pour ne pas avoir déféré à une mise en demeure fondée sur une interprétation nouvelle des dispositions du code des assurances, en rupture avec l’application faite par le passé par les autorités de contrôle compétentes de ces mêmes dispositions ; Les sociétés concernées ont formé un recours devant le Conseil d’Etat contre la décision de la Commission des sanctions du 11 mars 2016. Décision de la Commission des sanctions – procédures nos 2015-02 et 2015-03 Autorité de contrôle prudentiel et de résolution 2  la société B fait valoir (i) qu’elle ne saurait être sanctionnée pour ne pas avoir déféré à une mise en demeure fondée sur une interprétation nouvelle des dispositions du code des assurances, en rupture avec l’application faite par le passé par les autorités de contrôle compétentes de ces mêmes dispositions ; (ii) qu’elle a adopté en avril 2015

[...texte tronqué à 3000 caractères, voir export si besoin de plus...]

================================================================================
2018-06 — Décision de la Commission des sanctions n° 2018-06 du 11 juillet 2019 à l’égard de l'établissement A (2019-07-11) — 21 chunks
================================================================================
ÉTABLISSEMENT A Procédure no 2018-06 ––––– Blâme et sanction pécuniaire de 200 000 euros ––––– Audience du 26 juin 2019 Décision rendue le 11 juillet 2019 AUTORITÉ DE CONTRÔLE PRUDENTIEL ET DE RÉSOLUTION COMMISSION DES SANCTIONS ––––––––––––––– Vu la lettre du 25 septembre 2018 par laquelle le Président de l’Autorité de contrôle prudentiel et de résolution (ci-après l’« ACPR ») informe la Commission de ce que le Collège de supervision de l’ACPR (ci- après le « Collège »), statuant en sous-collège sectoriel de la banque, a décidé d’ouvrir une procédure disciplinaire à l’encontre d’un établissement de crédit (ci-après la « l’établissement A) , enregistré sous le no 2018-06 ; Vu la notification des griefs du 25 septembre 2018 ; Vu les mémoires en défense des 29 novembre 2018, 7 mars et 11 avril 2019 par lesquels l’établissement A conteste la régularité de la procédure et l’ensemble des griefs ; Vu les mémoires en réplique des 31 janvier et 27 mars 2019, par lesquels M. Emmanuel Constans, représentant du Collège, maintient l’ensemble des griefs notifiés ; Vu le rapport du 24 mai 2019 de M. Christian Lajoie, rapporteur, dans lequel celui-ci conclut que les 11 griefs notifiés sont établis, mais qu’au moins 3 d’entre eux peuvent être relativisés (griefs 4, 7 et 9) ; Vu les courriers du 24 mai 2019 convoquant les parties à l’audience et les informant de la composition de la Commission ; Vu les observations présentées le 7 juin 2019 par l’établissement A sur le rapport du rapporteur, par lesquelles il persiste dans sa contestation du bien-fondé de la poursuite, apporte des éléments complémentaires en défense sur chacun des griefs notifiés et demande, si une sanction devait être prononcée, qu’elle soit publiée sous une forme anonyme en raison du risque de réputation élevé d’une telle publication auprès de sa clientèle sous gestion privée ; Vu le courrier du 29 octobre 2018, remis à l’audience par l’établissement A, par lequel celui-ci informe la Banque de France de sa décision, qui fait notamment suite à une demande de retrait d’espèces non justifiée, de résilier la convention de compte qui le lie à la [banque B1 du pays A] ; Vu les autres pièces du dossier, notamment le rapport de contrôle du 9 avril 2018 ; Décision de la Commission des sanctions – procédure no 2018-06 Autorité de contrôle prudentiel et de résolution 2 Vu le code monétaire et financier (ci-après le « CMF »), notamment ses articles L. 561-4-1, L. 561-5, L. 561-5-1, L. 561-6, L. 561-10-2, L. 561-15, L. 561-32, L. 612-39, R. 561-1, R. 561-3, R. 561-7, R. 561-12, R. 561-38 et R. 612-35 à R. 612-52, dans leur rédaction en vigueur au moment du contrôle sur place ; Vu l’arrêté du 2 septembre 2009 pris en application de l'article R. 561-12 du code monétaire et financier et définissant des éléments d'information liés à la connaissance du client et de la relation d'affaires aux fins d'évaluation des risques de blanchiment de capitaux et de financement du terrorisme (ci-après « l’arrêté du 2 septemb

[...texte tronqué à 3000 caractères, voir export si besoin de plus...]

================================================================================
2019-02 — Décision de la Commission des sanctions n° 2019-02 du 10 décembre 2019 à l’égard de la société A (2019-12-10) — 8 chunks
================================================================================

In [9]:
# ── Export d'une décision en fichier texte, au besoin (lecture confortable) ──
def export_decision(decision_number: str):
    doc = documents.get(decision_number)
    if not doc:
        print(f"⚠️  {decision_number} introuvable")
        return
    path = EXPORT_DIR / f"{decision_number}.txt"
    path.write_text(
        f"{doc['title']}\nDate: {doc['date']}\nMotif brut: {doc['motif']}\n\n{doc['text']}",
        encoding="utf-8",
    )
    print(f"✅ Exporté: {path}")

# Exemple d'usage :
# export_decision("2010-01")

In [6]:
# ── Vue d'ensemble — toutes les décisions avec leur motif brut ──
overview = pd.DataFrame([
    {"decision_number": dn, "title": d["title"], "date": d["date"], "motif": d["motif"], "n_chunks": d["n_chunks"]}
    for dn, d in documents.items()
]).sort_values("decision_number")
overview

,decision_number,title,date,motif,n_chunks
0,2010-01,Décision de la Commission des sanctions n° 201...,2011-01-10,,21
1,2010-02,Décision de la commission des sanctions n° 201...,2011-02-28,capacité professionnelle ; condition d’honorab...,9
2,2010-05,Décision de la Commission des sanctions n° 201...,2011-05-26,lutte contre le blanchiment des capitaux ; con...,17
3,2010-06,Décision de la Commission des sanctions n° 201...,2011-12-16,contrôle des opérations et procédures internes...,46
4,2010-07,Décision de la Commission des sanctions n° 201...,2011-07-15,évaluation des risques ; contrôle interne,10
...,...,...,...,...,...
100,2025-01,Décision de la Commission des sanctions n°2025...,2026-05-13,protection de la clientèle ; respect des oblig...,19
101,263f8ed2f9d7,Décision de la Commission des sanctions du 13 ...,2018-06-13,lutte contre le blanchiment des capitaux et le...,14
102,3996b42891a4,Décision de la Commission des sanctions du 26 ...,2018-07-26,organisme d'assurance ; lutte contre le blanch...,29
103,4edd553ffea1,Décision de la Commission des sanctions du 13 ...,2018-06-13,lutte contre le blanchiment des capitaux et le...,25
104,e8b9e355beed,Décision de la Commission des sanctions du 3 j...,2018-07-03,lutte contre le blanchiment des capitaux et le...,18

In [12]:
# ── Distribution des combinaisons brutes de motifs (chaîne complète) ──
combo_counts = overview[overview["motif"] != ""]["motif"].value_counts()
combo_df = combo_counts.reset_index()
combo_df.columns = ["combinaison_motif", "count"]
combo_df

                                    combinaison_motif  count
0   lutte contre le blanchiment des capitaux et le...     18
1   établissement de crédit ; lutte contre le blan...      6
2   établissement de paiement ; lutte contre le bl...      5
3   lutte contre le blanchiment des capitaux et le...      4
4   organisme d'assurance ; lutte contre le blanch...      4
5   établissement de monnaie électronique ; lutte ...      4
6        contrats d’assurance sur la vie non réclamés      2
7   intermédiaire d’assurance ; obligation d’infor...      2
8              organisme d’assurance ; gel des avoirs      2
9   capacité professionnelle ; condition d’honorab...      1
10  lutte contre le blanchiment des capitaux ; con...      1
11  contrôle des opérations et procédures internes...      1
12          évaluation des risques ; contrôle interne      1
13                           exigence de fonds propre      1
14                           risque de non-conformité      1
15          contrôle interne ; organisation comptable      1
16  respect des obligations d’information et de co...      1
17  établissement de crédit ; droit au compte ; co...      1
18                                    capital minimum      1
19                                    droit au compte      1
20  insuffisance de fonds propre ; contrôle intern...      1
21                                   contrôle interne      1
22         contrats d’assurance sur la vie non réglés      1
23  intermédiation d'assurance ; condition d’honor...      1
24  non-respect de l’article L. 322-2-2 du code de...      1
25              abandon des poursuites disciplinaires      1
26                                      fonds propres      1
27  lutte contre le blanchiment et le financement ...      1
28  contrats d’assurance sur la vie non réglés ; o...      1
29  protection des fonds collectés ; lutte contre ...      1
30  cabinet de courtage ; respect des obligations ...      1
31  intermédiaire d'assurance ; respect de la cond...      1
32  intermédiaire d'assurance ; capacité professio...      1
33  lutte contre le blanchiment des capitaux et le...      1
34  lutte contre le blanchiment des capitaux et le...      1
35  intermédiaire d'assurance ; capacité professio...      1
36  institution de prévoyance ; règles de gouvernance      1
37  protection de la clientèle ; modification de c...      1
38  établissement de crédit ; intermédiaire d’assu...      1
39  lutte contre le blanchiment des capitaux et le...      1
40  intermédiaire d’assurances ; obligation d’info...      1
41  entreprise d’assurance ; protection de la clie...      1
42  établissement de paiement ; lutte contre le bl...      1
43  intermédiaire en financement participatif ; lu...      1
44  entreprise d’assurance ; lutte contre le blanc...      1
45  caisse de crédit municipal ; gouvernance, cont...      1
46  établissement de crédit ; protection de la cli...      1
47  organisme d’assurance ; information des assuré...      1
48  émetteur de monnaie électronique ; lutte contr...      1
49  organisme d’assurance ; contrats d’épargne ret...      1
50  entreprise d’investissement ; comptes d’épargn...      1
51  organisme d’assurance ; lutte contre le blanch...      1
52  établissement de crédit spécialisé ; lutte con...      1
53  établissement de monnaie électronique ; protec...      1
54  établissement de crédit ; contrôle interne ; m...      1
55  institution de prévoyance ; information des as...      1
56  établissement de crédit; contrôle interne ; lu...      1
57  établissement de crédit ; lutte contre le blan...      1
58  établissement de paiement étranger ; lutte con...      1
59  protection de la clientèle ; respect des oblig...      1

In [14]:
# ── Distribution du nombre de segments (griefs) par décision ──
overview["n_segments"] = overview["motif"].apply(
    lambda m: len([s.strip() for s in m.split(";") if s.strip()]) if m else 0
)

print("Min:", overview["n_segments"].min())
print("Max:", overview["n_segments"].max())
print()
print(overview["n_segments"].value_counts().sort_index())

Min: 0
Max: 4

n_segments
0     7
1    30
2    49
3    13
4     6
Name: count, dtype: int64

In [8]:
# ── Normalisation des apostrophes (unifie ' et ’) ──
def normalize_apostrophe(text: str) -> str:
    return text.replace("’", "'")

overview["motif_norm"] = overview["motif"].apply(normalize_apostrophe)

In [16]:
# ── Détection data-driven des segments "autonomes" (jamais seuls = suspects) ──
segments_alone = set()
segments_all = set()

for doc in documents.values():
    if not doc["motif"]:
        continue
    segments = [s.strip().lower() for s in doc["motif"].split(";") if s.strip()]
    segments_all.update(segments)
    if len(segments) == 1:
        segments_alone.add(segments[0])

never_alone = segments_all - segments_alone

print(f"Segments qui apparaissent seuls au moins une fois ({len(segments_alone)}) :")
for s in sorted(segments_alone):
    print(" -", s)

print(f"\nSegments qui n'apparaissent JAMAIS seuls ({len(never_alone)}) — candidats descripteurs :")
for s in sorted(never_alone):
    print(" -", s)

Segments qui apparaissent seuls au moins une fois (12) :
 - abandon des poursuites disciplinaires
 - capital minimum
 - contrats d’assurance sur la vie non réclamés
 - contrats d’assurance sur la vie non réglés
 - contrôle interne
 - droit au compte
 - exigence de fonds propre
 - fonds propres
 - lutte contre le blanchiment des capitaux et le financement du terrorisme
 - lutte contre le blanchiment et le financement du terrorisme
 - respect des obligations d’information et de conseil précontractuels
 - risque de non-conformité

Segments qui n'apparaissent JAMAIS seuls (57) — candidats descripteurs :
 - cabinet de courtage
 - caisse de crédit municipal
 - capacité professionnelle
 - changeur manuel
 - comptes d’épargne salariale
 - condition d’honorabilité
 - condition d’honorabilité des dirigeants
 - contrats d’épargne retraite
 - contrats en déshérence
 - contrôle des opérations et procédures internes
 - devoir de conseil
 - déshérence
 - entreprise d’assurance
 - entreprise d’investissement
 - gel des avoirs
 - gouvernance, contrôle de la conformité
 - information des assurés
 - institution de prévoyance
 - insuffisance de fonds propre
 - intermédiaire d'assurance
 - intermédiaire d’assurance
 - intermédiaire d’assurances
 - intermédiaire en financement participatif
 - intermédiation d'assurance
 - lutte contre la déshérence
 - lutte contre le blanchiment des capitaux
 - maîtrise des risques
 - maîtrise des risques de crédit
 - modification de contrats d’assurance
 - non-respect d'une mise en demeure
 - non-respect de l’article l. 322-2-2 du code des assurances
 - non-respect d’une mise en demeure
 - non-respect d’une mise en demeure du collège de l’acpr
 - obligation d'information
 - obligation d’identification des assurés décédés
 - obligation d’information
 - organisation comptable
 - organisme d'assurance
 - organisme d’assurance
 - protection de la clientèle
 - protection des fonds collectés
 - protection des fonds reçus des clients
 - relations avec le superviseur
 - respect de la condition d’honorabilité
 - respect des obligations d’information et de conseil
 - respect des obligations d’information précontractuelle, du devoir de conseil et de l’obligation d’agir au mieux des intérêts du client
 - risque de crédit
 - règles de gouvernance
 - succursale
 - système de surveillance et maîtrise des risques
 - émetteur de monnaie électronique
 - établissement de crédit
 - établissement de crédit spécialisé
 - établissement de monnaie électronique
 - établissement de paiement
 - établissement de paiement étranger
 - évaluation des risques

In [17]:
# ── Recalcul segments_alone / never_alone sur motif normalisé + fréquence totale ──
segments_alone = set()
segment_total_count = Counter()

for motif in overview["motif_norm"]:
    if not motif:
        continue
    segments = [s.strip().lower() for s in motif.split(";") if s.strip()]
    segment_total_count.update(segments)
    if len(segments) == 1:
        segments_alone.add(segments[0])

never_alone_df = pd.DataFrame(
    [(s, c) for s, c in segment_total_count.items() if s not in segments_alone],
    columns=["segment", "total_count"],
).sort_values("total_count", ascending=False)

# never_alone_df

In [ ]:
# ── Réveil de sg-embedding sur OVH + récupération des embeddings des segments ──
import httpx
import asyncio
import time
import numpy as np

OVH_ML_HOST = "51.68.130.23"
ORCHESTRATOR_PORT = 8080
EMBEDDING_PORT = 8004

WAKE_URL = f"http://{OVH_ML_HOST}:{ORCHESTRATOR_PORT}/wake/sg-embedding"
EMBED_URL = f"http://{OVH_ML_HOST}:{EMBEDDING_PORT}/embed"

# 1. Réveil du service
with httpx.Client(timeout=30.0) as client:
    wake_resp = client.post(WAKE_URL)
    wake_resp.raise_for_status()
    print("Wake:", wake_resp.json())

# 2. Attente du démarrage (service on-demand, peut prendre quelques secondes à charger le modèle)
print("Attente du démarrage du service...")
time.sleep(15)

# 3. Appel batch pour les 65 segments — avec retry en cas de service pas encore prêt
def get_embeddings_with_retry(texts, max_retries=5, wait_seconds=5):
    for attempt in range(max_retries):
        try:
            with httpx.Client(timeout=60.0) as client:
                resp = client.post(EMBED_URL, json={"texts": texts})
                resp.raise_for_status()
                return resp.json()["embeddings"]
        except (httpx.ConnectError, httpx.HTTPStatusError) as e:
            print(f"Tentative {attempt + 1}/{max_retries} échouée: {e} — nouvelle tentative dans {wait_seconds}s")
            time.sleep(wait_seconds)
    raise RuntimeError("Service embedding indisponible après plusieurs tentatives")

all_segments_list = sorted(segment_total_count.keys())
segment_embeddings = get_embeddings_with_retry(all_segments_list)

X_segments = np.array(segment_embeddings)
print(f"Embeddings récupérés : {X_segments.shape} ({len(all_segments_list)} segments, {X_segments.shape[1]} dimensions)")

Wake: {'status': 'ok', 'service': 'sg-embedding'}
Attente du démarrage du service...
Embeddings récupérés : (65, 768) (65 segments, 768 dimensions)

In [19]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from collections import defaultdict


# ── Étape 1 (TF-IDF au lieu d'embeddings) : lots équilibrés via KMeans sur TF-IDF ──
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(analyzer="word", ngram_range=(1, 2))
X_tfidf = vectorizer.fit_transform(all_segments_list).toarray()

BATCH_SIZE_TARGET = 12
n_batches = max(1, len(all_segments_list) // BATCH_SIZE_TARGET)

km_batch = KMeans(n_clusters=n_batches, random_state=42, n_init=10)
batch_labels = km_batch.fit_predict(X_tfidf)

batches = defaultdict(list)
for segment, label in zip(all_segments_list, batch_labels):
    batches[label].append(segment)

for label, members in batches.items():
    print(f"Lot {label} ({len(members)} segments)")

# Lot 0 (8 segments)
# Lot 2 (14 segments)
# Lot 4 (29 segments)
# Lot 1 (10 segments)
# Lot 3 (4 segments)

Lot 0 (8 segments)
Lot 2 (14 segments)
Lot 4 (29 segments)
Lot 1 (10 segments)
Lot 3 (4 segments)

In [20]:
# ── Étape 2 : regroupement LLM par lot ──
import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
# OLLAMA_MODEL = "gemma3:12b"
# OLLAMA_MODEL = "mistral"
OLLAMA_MODEL = "mistral-nemo"

# ── Regroupement des segments bruts en concepts canoniques (mistral-nemo) ──
# ── Regroupement des segments bruts en concepts canoniques (mistral-nemo, schéma strict) ──
GROUPING_PROMPT = """Tu es un expert en réglementation bancaire et assurantielle française (ACPR).

Voici une liste de segments de texte extraits de motifs de sanction ACPR. Plusieurs segments
désignent en réalité le MÊME concept, juste avec une formulation différente (singulier/pluriel,
synonymes, variantes orthographiques). Ta tâche : regrouper ces segments en concepts canoniques.

Règles :
- Chaque segment de la liste doit appartenir à exactement un groupe.
- Un concept canonique peut n'avoir qu'un seul membre si aucune variante n'existe.
- Donne un nom court et clair à chaque concept canonique (en français, sans majuscules).
- Ne fusionne PAS des concepts différents sous prétexte qu'ils sont liés thématiquement.

Segments à regrouper :
{segments_list}

Exemple de réponse attendue (structure à respecter EXACTEMENT, clés "canonical" et "members") :
{{"groups": [
  {{"canonical": "lutte contre le blanchiment", "members": ["lutte contre le blanchiment des capitaux et le financement du terrorisme", "lutte contre le blanchiment des capitaux"]}},
  {{"canonical": "gel des avoirs", "members": ["gel des avoirs"]}}
]}}
"""

GROUPING_SCHEMA = {
    "type": "object",
    "properties": {
        "groups": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "canonical": {"type": "string"},
                    "members": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["canonical", "members"],
            },
        },
    },
    "required": ["groups"],
}

def group_batch(segments_batch):
    segments_numbered = "\n".join(f"- {s}" for s in segments_batch)
    response = requests.post(OLLAMA_URL, json={
        "model": "mistral-nemo",
        "prompt": GROUPING_PROMPT.format(segments_list=segments_numbered),
        "stream": False,
        "format": GROUPING_SCHEMA,
        "options": {"num_ctx": 4096, "temperature": 0, "num_predict": 2048},
    })
    return json.loads(response.json()["response"])["groups"]

first_pass_groups = []
for label, members in batches.items():
    groups = group_batch(members)
    first_pass_groups.extend(groups)
    print(f"Lot {label} → {len(groups)} concepts")

print(f"\nTotal après 1ère passe : {len(first_pass_groups)} concepts canoniques")

Lot 0 → 5 concepts
Lot 2 → 8 concepts
Lot 4 → 15 concepts
Lot 1 → 4 concepts
Lot 3 → 2 concepts

Total après 1ère passe : 34 concepts canoniques

In [21]:
# ── Vérification : tous les segments sont-ils bien couverts après la 1ère passe ? ──
covered = []
for g in first_pass_groups:
    covered.extend(g["members"])

missing_after_pass1 = set(all_segments_list) - set(covered)
print("Manquants après 1ère passe:", missing_after_pass1)

Manquants après 1ère passe: {'organisation comptable', 'lutte contre la déshérence', "intermédiaire d'assurances", 'cabinet de courtage', "modification de contrats d'assurance", 'contrôle des opérations et procédures internes'}

In [22]:
# ── Réconciliation automatique : les manquants deviennent leurs propres concepts ──
missing_after_pass1 = set(all_segments_list) - set(covered)

for seg in missing_after_pass1:
    first_pass_groups.append({"canonical": seg, "members": [seg]})

print(f"Total après réconciliation : {len(first_pass_groups)} concepts canoniques")

# Vérification finale — plus aucun manquant possible par construction
covered_final = []
for g in first_pass_groups:
    covered_final.extend(g["members"])
assert set(covered_final) == set(all_segments_list), "Il manque encore des segments !"
print("✅ Tous les segments sont couverts")

Total après réconciliation : 40 concepts canoniques
✅ Tous les segments sont couverts

In [23]:
# ── Passe 2 : consolidation finale sur les concepts canoniques de la passe 1 ──
# canonical_names_pass1 = [g["canonical"] for g in first_pass_groups]
# final_groups = group_batch(canonical_names_pass1)  # réutilise la même fonction, un seul appel

pass1_with_context = []
for g in first_pass_groups:
    members_sample = ", ".join(g["members"][:3])  # jusqu'à 3 membres en exemple
    pass1_with_context.append(f"{g['canonical']} (ex: {members_sample})")

final_groups = group_batch(pass1_with_context)

print(f"Après consolidation : {len(final_groups)} concepts canoniques finaux")
pd.DataFrame([
    {"canonical": g["canonical"], "n_members": len(g["members"]), "members": ", ".join(g["members"])}
    for g in final_groups
])

Après consolidation : 34 concepts canoniques finaux

,canonical,n_members,members
0,maîtrise des risques,3,"maîtrise des risques, maîtrise des risques de ..."
1,condition d'honorabilité,3,"condition d'honorabilité des dirigeants, confo..."
2,gel des avoirs,1,gel des avoirs
3,abandon des poursuites disciplinaires,1,abandon des poursuites disciplinaires
4,obligation d'identification,1,obligation d'identification des assurés décédés
5,établissement de crédit,2,"établissement de crédit, établissement de créd..."
6,monnaie électronique,2,"émetteur de monnaie électronique, établissemen..."
7,paiement,2,"établissement de paiement, établissement de pa..."
8,caisse de crédit municipal,1,caisse de crédit municipal
9,institution de prévoyance,1,institution de prévoyance
10,fonds propres,2,"exigence de fonds propre, insuffisance de fond..."
11,risque,2,"risque de crédit, risque de non-conformité"
12,gouvernance,2,"règles de gouvernance, contrôle interne"
13,capital réglementaire,2,"capital minimum, fonds propres"
14,changement manuel,1,changeur manuel
15,comptes d'épargne salariale,1,comptes d'épargne salariale
16,contrats d'assurance-vie non réclamés,1,contrats d'assurance sur la vie non réclamés
17,contrats d'assurance-vie non réglés,1,contrats d'assurance sur la vie non réglés
18,épargne retraite,1,contrats d'épargne retraite
19,contrats en déshérence,2,"déshérence, contrats en déshérence"
20,protection des fonds collectés,3,"protection de la clientèle, protection des fon..."
21,succursale bancaire,1,succursale
22,devoir de conseil,3,"devoir de conseil, respect des obligations d'i..."
23,information des assurés,3,"information des assurés, obligation d'informat..."
24,non-respect de mise en demeure,2,"non-respect d'une mise en demeure, non-respect..."
25,respect de la réglementation assurantielle,1,non-respect de l'article l. 322-2-2 du code de...
26,lutte contre le blanchiment et le financement ...,3,lutte contre le blanchiment des capitaux et le...
27,relations avec l'autorité de supervision,1,relations avec le superviseur
28,organisation comptable,1,organisation comptable
29,lutte contre la déshérence,1,lutte contre la déshérence
30,intermédiaire d'assurances,3,"intermédiaire d'assurances, intermédiation d'a..."
31,cabinet de courtage,1,cabinet de courtage
32,modification de contrats d'assurance,1,modification de contrats d'assurance
33,contrôle des opérations et procédures internes,1,contrôle des opérations et procédures internes

In [24]:
# ── Reconstruction : segment brut → concept canonique final ──
# D'abord, mapping segment brut -> nom du concept de la passe 1
segment_to_pass1 = {}
for g in first_pass_groups:
    for seg in g["members"]:
        segment_to_pass1[seg] = g["canonical"]

# Puis, mapping nom concept passe 1 -> concept final (passe 2)
pass1_to_final = {}
for g in final_groups:
    for member in g["members"]:
        pass1_to_final[member] = g["canonical"]

# Chaîne complète : segment brut -> concept final
segment_to_final = {}
for seg, pass1_name in segment_to_pass1.items():
    final_name = pass1_to_final.get(pass1_name, pass1_name)  # fallback si absent de la passe 2
    segment_to_final[seg] = final_name

# Vérification
missing_final = set(all_segments_list) - set(segment_to_final.keys())
print("Segments non mappés:", missing_final)

# Vue d'ensemble
final_mapping_df = pd.DataFrame([
    {"segment_brut": seg, "concept_final": final} for seg, final in segment_to_final.items()
]).sort_values("concept_final")
final_mapping_df

final_mapping_df.to_csv("final_mapping_df.csv", sep=";", index=False, encoding="utf-8")

Segments non mappés: set()

In [25]:
# ── Classification ENTITY/GRIEF sur les concepts finaux (un par un, liste courte) ──

# ── Annotation sémantique des segments via Ollama local

# ── Classification par concept, avec sortie par segment membre ──
PER_SEGMENT_PROMPT = """Tu es un expert en réglementation bancaire et assurantielle française (ACPR).

Voici un groupe de segments qui désignent tous le même concept de fond : "{concept}"
Segments du groupe : {members}

Pour CHAQUE segment du groupe, classe-le dans une seule des deux catégories :
- ENTITY : catégorie/statut réglementaire d'entité (ex: établissement de crédit, organisme d'assurance)
- GRIEF : véritable motif de manquement/sanction (ex: lutte contre le blanchiment, gel des avoirs, contrôle interne)

Réponds UNIQUEMENT en JSON strict, un objet par segment, avec EXACTEMENT ces clés :
{{"annotations": [{{"segment": "...", "categorie": "ENTITY" ou "GRIEF", "justification": "..."}}, ...]}}
"""

PER_SEGMENT_SCHEMA = {
    "type": "object",
    "properties": {
        "annotations": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "segment": {"type": "string"},
                    "categorie": {"type": "string"},
                    "justification": {"type": "string"},
                },
                "required": ["segment", "categorie", "justification"],
            },
        },
    },
    "required": ["annotations"],
}

concept_to_members = final_mapping_df.groupby("concept_final")["segment_brut"].apply(list).to_dict()

all_segment_annotations = []
for concept, members in concept_to_members.items():
    members_str = ", ".join(members)
    response = requests.post(OLLAMA_URL, json={
        "model": "mistral-nemo",
        "prompt": PER_SEGMENT_PROMPT.format(concept=concept, members=members_str),
        "stream": False,
        "format": PER_SEGMENT_SCHEMA,
        "options": {"temperature": 0},
    })
    result = json.loads(response.json()["response"])
    for ann in result["annotations"]:
        ann["concept_final"] = concept
    all_segment_annotations.extend(result["annotations"])

all_segment_annotations_df = pd.DataFrame(all_segment_annotations)
print(f"{len(all_segment_annotations_df)} segments annotés (attendu: 65)")
all_segment_annotations_df

66 segments annotés (attendu: 65)

,segment,categorie,justification,concept_final
0,abandon des poursuites disciplinaires,GRIEF,Il s'agit d'un motif de manquement/sanction,abandon des poursuites disciplinaires
1,cabinet de courtage,ENTITY,Un cabinet de courtage est une entité qui agit...,cabinet de courtage
2,caisse de crédit municipal,ENTITY,Les caisses de crédit municipales sont des éta...,caisse de crédit municipal
3,exigence de fonds propre,ENTITY,Cette exigence s'applique aux entités soumises...,capital réglementaire
4,insuffisance de fonds propre,GRIEF,Une insuffisance de fonds propres peut entraîn...,capital réglementaire
...,...,...,...,...
61,risque de non-conformité,GRIEF,Le risque de non-conformité est un motif de ma...,risque
62,succursale bancaire,ENTITY,Une succursale bancaire est une entité qui app...,succursale bancaire
63,contrats d'épargne retraite,ENTITY,Les contrats d'épargne retraite sont des produ...,épargne retraite
64,établissement de crédit,ENTITY,Un établissement de crédit est une entité régl...,établissement de crédit
65,établissement de crédit spécialisé,ENTITY,"Bien que spécialisé, un établissement de crédi...",établissement de crédit

In [26]:
all_segment_annotations_df["categorie"].value_counts()

categorie
ENTITY    36
GRIEF     30
Name: count, dtype: int64

In [27]:
dupes = all_segment_annotations_df[all_segment_annotations_df["segment"].duplicated(keep=False)]
dupes.sort_values("segment")

Empty DataFrame
Columns: [segment, categorie, justification, concept_final]
Index: []

In [28]:
consistency_check = all_segment_annotations_df.groupby("concept_final")["categorie"].nunique()
inconsistent_concepts = consistency_check[consistency_check > 1]
print("Concepts avec categorie incohérente entre leurs membres:")
inconsistent_concepts

Concepts avec categorie incohérente entre leurs membres:

concept_final
capital réglementaire             2
condition d'honorabilité          2
gouvernance                       2
information des assurés           2
intermédiaire en assurance        2
protection des fonds collectés    2
risque                            2
Name: categorie, dtype: int64

In [29]:
# ── Filtrer : ne garder que les vrais segments bruts d'origine ──
all_segment_annotations_df_clean = all_segment_annotations_df[
    all_segment_annotations_df["segment"].isin(all_segments_list)
].copy()

print(f"{len(all_segment_annotations_df_clean)} segments valides (attendu: 65)")

# Vérifier ce qui a été filtré
dropped = all_segment_annotations_df[~all_segment_annotations_df["segment"].isin(all_segments_list)]
print("\nLignes filtrées (probablement des noms de concepts) :")
dropped

63 segments valides (attendu: 65)

Lignes filtrées (probablement des noms de concepts) :

,segment,categorie,justification,concept_final
28,gouvernance,ENTITY,La gouvernance concerne l'ensemble des règles ...,gouvernance
29,contrôle de la conformité,GRIEF,Le contrôle de la conformité est une mesure pr...,gouvernance
62,succursale bancaire,ENTITY,Une succursale bancaire est une entité qui app...,succursale bancaire

In [30]:
# ── Segments réellement manquants après nettoyage ──
missing_segments = set(all_segments_list) - set(all_segment_annotations_df_clean["segment"])
print(f"{len(missing_segments)} segments manquants :")
missing_segments

2 segments manquants :

{'gouvernance, contrôle de la conformité', 'succursale'}

In [31]:
manual_fixes = pd.DataFrame([
    {"segment": "gouvernance, contrôle de la conformité", "categorie": "GRIEF", "justification": "manquement de gouvernance/conformité — ajout manuel", "concept_final": "gouvernance"},
    {"segment": "succursale", "categorie": "ENTITY", "justification": "statut réglementaire d'entité — ajout manuel", "concept_final": "succursale bancaire"},
])

all_segment_annotations_final = pd.concat([
    all_segment_annotations_df_clean[~all_segment_annotations_df_clean["segment"].isin(["gouvernance", "contrôle de la conformité", "succursale bancaire"])],
    manual_fixes,
], ignore_index=True)

print(f"Total final: {len(all_segment_annotations_final)} (attendu: 65)")

Total final: 65 (attendu: 65)

In [32]:
# ── Revérification de cohérence sur la version finale ──
consistency_final = all_segment_annotations_final.groupby("concept_final")["categorie"].agg(lambda x: list(x))
inconsistent_final = consistency_final[consistency_final.apply(lambda x: len(set(x)) > 1)]
inconsistent_final

concept_final
capital réglementaire             [ENTITY, GRIEF, ENTITY, ENTITY]
condition d'honorabilité           [ENTITY, GRIEF, ENTITY, GRIEF]
information des assurés                    [GRIEF, GRIEF, ENTITY]
intermédiaire en assurance                [ENTITY, GRIEF, ENTITY]
protection des fonds collectés            [ENTITY, GRIEF, ENTITY]
risque                                            [ENTITY, GRIEF]
Name: categorie, dtype: object

In [33]:
# ── Résolution manuelle des 8 concepts incohérents (une seule catégorie par concept) ──
concept_final_category = {
    "capital réglementaire": "GRIEF",              # exigences de fonds propres non respectées
    "condition d'honorabilité": "ENTITY",          # prérequis d'agrément, pas un manquement en soi
    # "gouvernance": "GRIEF",                         # manquement de gouvernance/contrôle de la conformité
    "information des assurés": "GRIEF",             # devoir d'information non respecté
    "intermédiaire en assurance": "ENTITY",        # statut réglementaire
    # "paiement": "ENTITY",                           # établissement de paiement, statut d'entité
    "protection des fonds collectés": "GRIEF",     # manquement à l'obligation de protection des fonds
    "risque": "GRIEF",                              # déficience de maîtrise des risques
}

# Appliquer la résolution : override sur tous les segments des concepts concernés
for concept, cat in concept_final_category.items():
    all_segment_annotations_final.loc[
        all_segment_annotations_final["concept_final"] == concept, "categorie"
    ] = cat

# Vérification finale : plus aucune incohérence possible
final_check = all_segment_annotations_final.groupby("concept_final")["categorie"].nunique()
assert (final_check == 1).all(), "Incohérence résiduelle !"
print("✅ Taxonomie ENTITY/GRIEF figée, aucune incohérence")

✅ Taxonomie ENTITY/GRIEF figée, aucune incohérence

In [34]:
# ── Export de la taxonomie validée ──
taxonomy_export = all_segment_annotations_final[["segment", "concept_final", "categorie"]].copy()
taxonomy_export.to_json("taxonomy_mapping.json", orient="records", force_ascii=False, indent=2)
taxonomy_export.to_csv("taxonomy_mapping.csv", index=False)
print(f"Export : {len(taxonomy_export)} segments")

Export : 65 segments

In [11]:
taxonomy_export = pd.read_csv("taxonomy_mapping.csv")
# ── Distribution réelle par grief final (après taxonomie, décomposé) ──
grief_only_mapping = {
    row["segment"]: row["concept_final"]
    for row in taxonomy_export.to_dict("records")
    if row["categorie"] == "GRIEF"
}

def get_griefs_for_decision(motif: str) -> list:
    if not motif:
        return []
    segments = [s.strip().lower() for s in normalize_apostrophe(motif).split(";") if s.strip()]
    griefs = {grief_only_mapping[s] for s in segments if s in grief_only_mapping}
    return list(griefs)

overview["griefs_finaux"] = overview["motif"].apply(get_griefs_for_decision)

# Compter dans combien de décisions chaque grief apparaît
grief_decision_counts = Counter()
for griefs in overview["griefs_finaux"]:
    grief_decision_counts.update(griefs)

grief_freq_df = pd.DataFrame(
    grief_decision_counts.most_common(), columns=["grief_final", "n_decisions"]
)
grief_freq_df

                                          grief_final  n_decisions
0   lutte contre le blanchiment et le financement ...           58
1                                         gouvernance           16
2                             information des assurés            8
3                      protection des fonds collectés            7
4                                   devoir de conseil            6
5                               capital réglementaire            4
6                                      gel des avoirs            4
7                      non-respect de mise en demeure            3
8                              contrats en déshérence            3
9                                              risque            2
10              contrats d'assurance-vie non réclamés            2
11                contrats d'assurance-vie non réglés            2
12     contrôle des opérations et procédures internes            1
13         respect de la réglementation assurantielle            1
14              abandon des poursuites disciplinaires            1
15                        obligation d'identification            1
16               modification de contrats d'assurance            1
17                         lutte contre la déshérence            1